--관리자 영역
SELECT*FROM DBA_TABLESPACES;
--사용자 삭제
DROP USER iouser CASCADE;
--테이블스페이스 삭제
DROP TABLESPACE iolistDB
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;
--iolist를위한 tablespace생성
CREATE TABLESPACE iolistDB
DATAFILE 'C:/oraclexe/data/iolist.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

CREATE USER iouser IDENTIFIED BY iouser
DEFAULT TABLESPACE iolistDB;

GRANT DBA TO iouser;
--오라클의 SYSTEM값
SELECT*FROM DBA_PROFILES;
--오라클에 새로등록된 사용자의 PASSWORD만료일자
--기본값이 180으로 되어있어서
--새로운 사용자 등록후 비번을 변경하지않으면
--180일후 접속이 불가능해진다
SELECT*FROM DBA_PROFILES
WHERE resource_name='PASSWORD_LIFE_TIME';
--사용자의 PASSWORD만료일자를 무제한으로 변경
ALTER PROFILE 
DEFAULT LIMIT PASSWORD_LIFE_TIME
UNLIMITED;



