--2021-04-30 관리자 영역
DROP USER bookuser CASCADE;

DROP TABLESPACE RentBookDB
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

CREATE TABLESPACE RentBookDB
DATAFILE 'C:/oraclexe/data/rentbook'
SIZE 1M AUTOEXTEND ON NEXT 1K;

CREATE USER bookuser IDENTIFIED BY bookuser
DEFAULT TABLESPACE RentBookDB;

GRANT DBA TO bookuser;
